import styles from './MainLayout.module.css'
import Head from 'next/head'
import { Navbar } from '../Navbar'
import { FC } from 'react'


export const MainLayout: FC = ({children}) => {
  return (

    <div className={styles.container}>

      <Head>
        <title>Mi primera app Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <Navbar />
      
      <main className={styles.main}>
        {children}
      </main>

    </div>
  )
}
